image: docker:latest
stages:
  - build
  - deploy
# see: http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
variables:
   DOCKER_DRIVER: overlay2
   APP: govcms8
   IMAGE_TAG: registry.gitlab.com/markf/$APP

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
   stage: build
   script:
   - echo "Building Docker image ..."
   - docker build -t $IMAGE_TAG .


deploy-staging:
   stage: deploy
   script:
   - echo "Pushing to master branch repository on Gitlab."
   - docker push $IMAGE_TAG:master
   environment:
     name: staging
   only:
   - master

deploy-production:
   stage: deploy
   script:
   - echo "Pushing to PRODUCTION repository on Docker Cloud"
   - docker push # TODO
   environment:
     name: production
   when: manual
   only:
   - production