image: docker:latest

services:
   - docker:dind

variables:
   DOCKER_DRIVER: overlay2
   APP: govcms8
   IMAGE_TAG: registry.gitlab.com/markf/$APP

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
   stage: build
   script:
   - docker build -t $IMAGE_TAG .
   - docker save $IMAGE_TAG -o image.tar
   cache:
     key: image
     paths:
     - image.tar

deploy:
   stage: deploy
   script:
   - docker load -i image.tar
   - docker push $IMAGE_TAG
   cache:
     key: image
     paths:
     - image.tar
     policy: pull
   only:
   - master
