image: docker:latest
stages:
  - build
  - deploy
# see: http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
variables:
   DOCKER_DRIVER: overlay2
   REPO: registry.gitlab.com/plenum/webserver-image

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
   stage: build
   script:
   - echo "Building Docker image ..."
   - docker build -t $REPO .


deploy-staging:
   stage: deploy
   script:
   - echo "Pushing to master branch on Gitlab."
   - docker push $REPO:master
   environment:
     name: staging
   only:
   - master

deploy-production:
   stage: deploy
   script:
   - echo "Push to production branch on Gitlab"
   - docker push $REPO:production
   environment:
     name: production
   when: manual
   only:
   - production