stages:
  - build
  

phpunit:
  image: markfuller/govcms8
  script:
    - cd /var/www/html
    - composer require phpunit/phpunit
    - cd docroot/core
    - ../../bin/phpunit --testsuite=unit
  stage: build
    