stages:
  - build
  

phpunit:
  image: markfuller/govcms8
  script:
    - cd /var/www/html
    - composer require phpunit/phpunit
    - ls ..
    - ls
    - ls bin
    - ls vendor
    - vendor/bin/phpunit --testsuite=unit
  stage: build
    