image: docker:latest
stages:
  - build
  - deploy

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
   stage: build
   script:
   - echo "Building Docker image ..."
   - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

deploy-staging:
   stage: deploy
   script:
   - echo "Pushing to master branch on Gitlab."
   - docker push $REPO:master
   environment:
     name: staging
   only:
   - master

deploy-production:
   stage: deploy
   script:
   - echo "Push to production branch on Gitlab"
   - docker push $REPO:production
   environment:
     name: production
   when: manual
   only:
   - production