image: docker:latest
stages:
  - build
  - test
  - deploy
services:
   - docker:dind

variables:
   DOCKER_DRIVER: overlay2
   APP: govcms8
   IMAGE_TAG: registry.gitlab.com/markf/$APP

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
   stage: build
   script:
   - docker build -t $IMAGE_TAG .

test:
  image: $IMAGE_TAG:master
  stage: test
  script:
    - composer global require drush/drush:7.*
    - composer global require drupal/coder
    - export PATH="$PATH:/var/www/html/vendor/bin"
    - phpcs --config-set installed_paths /var/www/html/vendor/drupal/coder/coder_sniffer

deploy:
   stage: deploy
   script:
   - docker push $IMAGE_TAG
   only:
   - master
