image: docker:latest

services:
- docker:dind

stages:
- build
- deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

Build:
  stage: build
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

Staging:
  stage: deploy
  script:
  - docker_tag push $CI_BUILD_SHA staging
  - docker_cloud service redeploy --sync staging.deployment-demo
  except:
  - master
  environment: staging


Production:
  stage: deploy
  script:
  - docker_tag_push $CI_BUILD_SHA production
  - docker_cloud service redeploy --sync production.deployment-demo
  only:
  - master
  environment: production
